:PROPERTIES:
:ID:       0dd5cfd0-e2d1-4d3e-8d08-a3e9b18bf636
:END:
#+title: Cache Coherency Protocol
#+filetags: :computer-science:concurrency:

Cache coherency protocol is a communication mechanism that permits
cores to share data thus that every core has the same view of data.

Most CPUs either use [[id:46e295cc-03ab-47f8-af74-efff48cb01f2][MESI Protocol]] or MEOSI protocol.

Optimizations of these protocol will delay the change of state of some
cache lines. These optimizations would not cause detectable difference
in a single thread program. However, they are one of the [[id:736271f7-d51f-4b36-9e41-2d0fe784bbe3][Causes of
Data Race Bugs]] in multithread-programs.

To summarize, because of optimizations of cache coherency protocols,
in a multithread-program, the relative order of read/write operations
to two different memory locations in one thread could not be
guaranteed appearing same in another thread. To solve problems caused
by these optimizations, CPU introduces [[id:a97e8322-3179-484d-8ea5-504683ecf8c5][Memory Fence]]s.
